name: ci
on:
  push:


jobs:
  run:
    runs-on: ubuntu-latest
    steps:

    # Prepare

    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Install Task
      uses: arduino/setup-task@v2
      with:
        version: 3.x
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    # Validate

    - name: Test
      run: task test

    # Push

    - if: github.ref == 'refs/heads/main'
      name: Login to Docker Registry
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - if: github.ref == 'refs/heads/main'
      name: Push image
      run: tesk push
